### ISSUE TITLE
support for tables

### ISSUE THREAD

**Issue by ghost** [tombensve/MarkdownDoc#16]
First of all thanks for this great plugin and your good work!

Do you plan to implement support for tables by any chance?

**Comment by tombensve** [comment]
Well, so far I have not thought about doing that, but there have been times when I've wanted to have support for tables though. One problem is that the Gruber markdown specification does not include tables, and I did not want to come up with some own table format that does not work elsewhere like GitHub. But apparently GitHub does support tables using the format described here:

http://www.tablesgenerator.com/markdown_tables

So if I implement tables it would be this format. 

So my answer to your question is: I'll put tables on the todo list, however do not expect anything too soon. This is hobby work when time allows, and I'm currently working on something else that I need to get done first. 

Pull requests are also welcome :-)

/Tommy
