### ISSUE TITLE
Can't find image resource that is relative to .md file

### ISSUE THREAD

**Issue by mih-kopylov** [tombensve/MarkdownDoc#18]
I've got a structure for PDF generator
```
|-index.md
|-images
|--|--image.jpg
|-manual
|--|--chapter1.md
```
And there's block in chapter1.md: `![](../images/image.jpg)` that's file relative to chapter1.md.

But I got FileNotFoundException with message `Invalid resource path: ../images/image.jpg!` in FileResource.groovy

It works only when I use image path that's relative to baseDir configuration parameter. But it's not comfortable.

Can you fix it please?

**Comment by mih-kopylov** [comment]
I can't create a PL, but here's an example - how to fix this issue.

```
                case DocFormat.Image:
                    writeImage((Image)docItem, pdfParagraph, context, paragraph.parseFile) // add original md file here
                    break
```

So `writeImage` becomes this
```
    private static void writeImage(@NotNull final Image image, @NotNull final PDFParagraph pdfParagraph,
                            @NotNull final PDFGeneratorContext context, @NotNull final File originalFile) {

        final PDFImage pdfImage = PDFImage.getInstance(new URL(context.fileResource.resolveUrl(image.url, originalFile))) //pass originalFile here
// other code here
```

And FileResource.getResourceFile becomes this
```
    File getResourceFile(@NotNull final String path, @Nullable File relativeFile) throws IOException {
        final File resourceFile

        if (relativeFile != null) {
            resourceFile = resolveFile(relativeFile, path);
            if (null != resourceFile) {
                return resourceFile
            }
        }
// other code here
```

Could you apply this please

**Comment by tombensve** [comment]
Hello Mikhail,

Thanks for a very good suggestion, and for providing the solution :-). Version 1.4.3 is now available.

/Tommy
