### ISSUE TITLE
NPE running the plugin 

### ISSUE THREAD

**Issue by bpteodor** [tombensve/MarkdownDoc#20]
This is probably just misconfiguration, but still a bit ugly. 

Here is the [exception.txt](https://github.com/tombensve/MarkdownDoc/files/459675/exception.txt).
My config:
`<plugin>
                        <groupId>se.natusoft.tools.doc.markdowndoc</groupId>
                        <artifactId>markdowndoc-maven-plugin</artifactId>
                        <version>1.4.4</version>
                        <executions>
                            <execution>
                                <id>generate-docs</id>
                                <goals>
                                    <goal>doc</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <generatorOptions>
                                        <generator>pdf</generator>
                                        <inputPaths>${project.basedir}/src/doc/.*.md</inputPaths>
                                    </generatorOptions>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>`

**Comment by tombensve** [comment]
Hello Teo,

You have forgotten to specify ’resultFile’, the output to write PDF result to. I agree that an NPE is not nice. It should produce a better error message in this case.

**Comment by pzalkind** [comment]
Hello Tommy,

I may have missed something obvious but I can't figure out what.

I get a similar error as  @bpteodor, I can provided the exception if needed.

Below is my config, do you see what is wrong ?? 
<plugin>
        <groupId>se.natusoft.tools.doc.markdowndoc</groupId>
        <artifactId>markdowndoc-maven-plugin</artifactId>
        <version>1.4.4</version>
        <executions>
          <execution>
            <id>generate-docs</id>
            <goals>
              <goal>doc</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
              <generatorOptions>
                <generator>pdf</generator>
                <generator>html</generator>
                <inputPaths>${project.basedir}/docs</inputPaths>
              </generatorOptions>
              <PDFGeneratorOptions>resultFile=${project.basedir}/docs/user-guide.pdf</PDFGeneratorOptions>
              <HTMLGeneratorOptions>resultFile=${project.basedir}/docs/user-guide.html</HTMLGeneratorOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>


Thanks in advance

**Comment by tombensve** [comment]
Hello Pierre,

Hmm, this was interesting. Assuming that maven passes the subtags of <generatorOptions> in order specified then <generator>html</generator> will overwrite <generator>pdf</generator> which in turn should have the effect of <PDFGeneratorOptions>...</PDFGeneratorOptions> being ignored. 

You should have a separate <execution>...</execution> for each generator execution. One for the PDF generator, and one for the HMTL generator. They cannot be mixed in the same.

This however does not explain an NPE. There are 3 required inputs in total: generator, inputPaths, and resultFile, and you provide all 3. 

Even if the problem goes away when you split it up into separate executions, I'm interested in the stacktrace, so please save it before you change :-).

**Comment by pzalkind** [comment]
Here is the stack trace, I hope you'll understand where this might be coming from !
[stacktrace_maven_mdDoc.txt](https://github.com/tombensve/MarkdownDoc/files/466790/stacktrace_maven_mdDoc.txt)
(I'm new to maven, so it might be something simple related to maven that I didn't set correctly)

I'm gonna try the changes you proposed I'll let you know if it solves the problem.

**Comment by tombensve** [comment]
I just found this issue again, and it seems to not have been solved. Since my GitHub stuff is done on my my free time, there are times when I don't have the time over, and it has unfortunately been a long such now due to work (on another planet in a different universe from which a lot of developers have fled ...). 

Anyhow I did notice one thing I apparently did not see before in your example above. 

From your example:
`<inputPaths>${project.basedir}/docs</inputPaths>`. 

From manual:

    <generatorOptions>
        <generator>pdf</generator>
        <inputPaths>
            Docs/parts/H1UserGuide.mdpart,
            Docs/MarkdownDoc.md,
            MavenPlugin/docs/.*.md,
            CommandLine/docs/.*.md,
            Library/docs/.*.md,
            Docs/parts/H1Licenses.mdpart,
            Docs/licenses.md,
            Docs/parts/H1LicenseTexts.mdpart,
            Docs/.*-.*.md
        </inputPaths>
        <parserOptions>option=value,....</parserOptions>
    </generatorOptions>

It is not enough to just specify a directory, you also need to specify file or files. Regexp wildcards can be used as in manual example. 

So your input line should look like this:
`<inputPaths>${project.basedir}/docs/.*.md</inputPaths>`. 

This should of course not throw an NPE! That is a clear bug.

**Comment by tombensve** [comment]
I leave this issue open until I have fixed the NPE.

**Comment by satbachansingh** [comment]
Hi ,

I am trying to consume the plugin. Below is my pom.xml. Is this issue impacting me or any other mistake is hitting me ? Is there any workaround for this?

<plugin>
				<groupId>se.natusoft.tools.doc.markdowndoc</groupId>
				<artifactId>markdowndoc-maven-plugin</artifactId>
				<version>1.2.9</version>
				<dependencies>
					<dependency>
						<groupId>se.natusoft.tools.codelicmgr</groupId>
						<artifactId>CodeLicenseManager-annotations-retention-source</artifactId>
						<version>2.1.1</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>generate-docs</id>
						<goals>
							<goal>doc</goal>
						</goals>
						<phase>install</phase>
						<configuration>			
							<generatorOptions>
								<generator>pdf</generator>								
								<inputPaths>${project.basedir}/docs/README.md</inputPaths>								
							</generatorOptions>
							<PDFGeneratorOptions>resultFile=${project.basedir}docs/user-guide.pdf</PDFGeneratorOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>	


I am getting below error . Can you please help here 

[INFO] --- markdowndoc-maven-plugin:1.2.9:doc (generate-docs) @ docker-docs ---
[WARNING] The POM for se.natusoft.tools.codelicmgr:CodeLicenseManager-annotations-retention-source:jar:2.0 is missing, no dependency information available
Parsing the following files:
    ##############################\docs\README.md
All parsed!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.982 s
[INFO] Finished at: 2017-10-31T11:27:12+05:30
[INFO] Final Memory: 12M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal se.natusoft.tools.doc.markdowndoc:markdowndoc-maven-plugin:1.2.9:doc (generate-docs) on project docker-docs: Execution generate-docs of goal se.natusoft.tools.doc.markdowndoc:markdowndoc-maven-plugin:1.2.9:doc failed. NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by tombensve** [comment]
I see one error in your plugin config:

`<PDFGeneratorOptions>resultFile=${project.basedir}/docs/user-guide.pdf</PDFGeneratorOptions>`

It should be:

`<PDFGeneratorOptions><resultFile>${project.basedir}/docs/user-guide.pdf</resultFile></PDFGeneratorOptions>`

The plugin is looking for the `<resultFile>...</resultFile>` tag, which is required, and in your case it will be null since you have not provided it.

I also see that you are running a rather old version of MarkdownDoc. I suggest that you go upp to latest 2.1.0. I think that the version you are using is still based on iText, while the 2.* versions are based on PDFBox.
