### ISSUE TITLE
default.mss is missing 'grey' definition

### ISSUE THREAD

**Issue by jvdvegt** [tombensve/MarkdownDoc#27]
The defualt.mss file is missing the definition for the color 'grey', but that color is referenced for the horizontal ruler. This causes a fatal exception when using the such ruler and de default MSS.

**Comment by tombensve** [comment]
Hmm, I'm for some reason not getting notifications to my mail when new issues are added! Just saw this. GitHub says that I should be getting notifications, but not to where ...

Anyhow, I have just noticed this problem myself. It is not a problem of "grey" not being defined, "Grey" is defined. I should make color name lookup case insensitive! 

I apparently added "grey" as color for "hr", without testing rendering a PDF with an "hr"! That was REALLY BAD of me! I'll fix this ASAP! 

/Tommy

**Comment by tombensve** [comment]
As a temporary workaround you can copy this:

https://github.com/tombensve/MarkdownDoc/blob/master/Library/src/main/resources/mss/default.mss

and add a "grey" entry, and then specify this mss file when generating.

**Comment by tombensve** [comment]
This is now fixed in version 2.1.3 just pushed to Bintray.
